### ISSUE TITLE
500 on select

### ISSUE THREAD

**Issue by louis030195** [supabase-community/supabase-swift#107]
# Bug report

## Describe the bug

Select returns 500

## To Reproduce

```swift
 let query = client.database
                .from("foos")
                .select(columns: "created_at")
                .order(column: "created_at", ascending: false)
                .limit(count: 1)

let created_at_list: [Date] = try await query.execute().value
// crash 500
```

## Expected behavior

Returns the rows

## System information

- OS: macOS

**Comment by louis030195** [comment]
removing the limit and order by fix the issue

**Comment by louis030195** [comment]
workaround for the order by:

`order(column: "created_at", ascending: false, nullsFirst: true)`

**Comment by grdsdev** [comment]
Tried to reproduce this using the upcoming v1 release (latest main), and I wasn't able to, so I assume this has been fixed.

I'm closing this issue, but feel free to re-open it if it persists after v1 release.

Thanks.
