### ISSUE TITLE
Add in ability to call supabase.auth.resend()

### ISSUE THREAD

**Issue by bwship** [supabase-community/supabase-swift#108]
# Feature request

## Is your feature request related to a problem? Please describe.

It seems that the resend has not been setup in the sdk - https://supabase.com/docs/reference/javascript/auth-resend

## Describe the solution you'd like

I would like to be able to call this to have the user resend the OTP email.

## Describe alternatives you've considered

I will have to use an edge function instead, which isn't ideal.

**Comment by scottybobandy** [comment]
+1 Would also love to see this implemented

**Comment by grsouza** [comment]
Hi, I haven't had much time recently to work on Supabase due to some other projects, feel free to send a PR over and I'll gladly review it.

**Comment by scottybobandy** [comment]
Would love to pick this up as a first issue - I can try and find some time in next couple weeks

**Comment by bwship** [comment]
@scottybobandy - any update on this?
