### ISSUE TITLE
Support filtering by `null` values

### ISSUE THREAD

**Issue by monsoir** [supabase-community/supabase-swift#112]
# Feature request

I have created a column called `deleted_at`, and want to use it to filter the deleted records. It's designed to be `null` or valued.

Find that the values passed to filter methods must be conformed to `URLQueryRepresentable` protocol, thus `nil` probably not work.
Find that `URLQueryRepresentable` finally requests a `String` value, then I tried using a string value as `"null"`, but Supabase returned 400 error.

Is there any way to use `null` value as a filter condition for now?
If not, a feature like that would be nice.

Thank you!

**Comment by monsoir** [comment]
Well, got it work.

Compare with the library using JavaScript, I should use `.is(column: "<column>", value: "null")`, `null` as a plain string

**Comment by Magnuti** [comment]
Can we add this to the official docs @grdsdev  ?

I mean an example like this `.is(column: "<column>", value: "null")`

**Comment by grdsdev** [comment]
Hi @Magnuti this has changed a bit since this issue was opened.

The `is` method now accepts a `Bool?`, since the only possible values for the is filter are `true`, `false`, or `nil`.

The `.is(column, value: nil)` works now.
