### ISSUE TITLE
Sign in with OTP

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#115]
## Describe the problem
Sign In With OTP kinda misleads that user would receive an OTP number like 4 or 6 digit when they are using email.

## Describe the improvement
It would be great if you can rename the function for email type that describes Sign in with magic link

**Comment by nijynot** [comment]
Looking at the documentation, it says that email should be possible to include a code in the email: https://supabase.com/docs/reference/swift/auth-signinwithotp

>Magic links and OTPs share the same implementation. To send users a one-time code instead of a magic link, [modify the magic link email template](https://supabase.com/dashboard/project/_/auth/templates) to include {{ .Token }} instead of {{ .ConfirmationURL }}.

**Comment by grdsdev** [comment]
Hi @pradeepb28 , thanks for the feedback, but unfortunately we try to have similar names between Supabase libraries, so I don't think a rename would fit here.

I suggest you start a discussion on https://github.com/orgs/supabase/discussions and see what everyone thinks about this.

And as @nijynot said, you can adjust your email template to include both the Token and the Magic Link.

Thanks.
