### ISSUE TITLE
Request for Basic Documentation

### ISSUE THREAD

**Issue by DrinkCupboard** [supabase-community/supabase-swift#12]
Any chance someone could find some time to add basic docs for Auth/Storage/Realtime? Would be super grateful! 🙏

**Comment by codeonomics** [comment]
@AngCosmin  - seems like auth relies on GoTrue, do you need help getting code completion to link with GoTrue or is it a case of documentation? Any insights that could be shared here around timelines? I'm happy to help. Would be great to use this lib for my iOS project... at the moment just going to use my own API...

**Comment by AngCosmin** [comment]
I just added some basic documentation for Auth if you are still interested 😄

**Comment by DrinkCupboard** [comment]
@AngCosmin Legend! Thanks! 🤘☺️
