### ISSUE TITLE
Sign in with apple stopped working properly recently

### ISSUE THREAD

**Issue by Li11leprince** [supabase-community/supabase-swift#122]
# Bug report

## Describe the bug

I am using `signInWithIdToken` method with apple provider for user auth. It looks like this:

```
    func authorizationController(
        controller: ASAuthorizationController,
        didCompleteWithAuthorization authorization: ASAuthorization
    ) {
        guard let credentials = authorization.credential as? ASAuthorizationAppleIDCredential,
              let identityToken = credentials.identityToken,
              let identityTokenString = String(data: identityToken, encoding: .utf8)
        else { return }
        if let firstName = credentials.fullName?.givenName,
           let lastName = credentials.fullName?.familyName {
            saveName(firstName: firstName, lastName: lastName)
        }
        handleCredentials(idToken: identityTokenString)
    }
```

And handle the token with:

```
    public func handleCredentials(idToken: String) async throws -> Credentials? {
        do {
            session = try await client.auth.signInWithIdToken(credentials:
                    .init(provider: .apple, idToken: idToken))
            guard let session = session else { return nil }
            
            let credentials = Credentials(
                accessToken: session.accessToken,
                refreshToken: session.refreshToken,
                expirationDate: Date() + TimeInterval(session.expiresIn)
            )
            return credentials
            
        } catch let error {
            throw error
        }
    }
```

It worked perfectly for a couple of months. But last month I started getting an error "the network connection was lost" on the ` session = try await client.auth.signInWithIdToken(credentials:
                    .init(provider: .apple, idToken: idToken))` method.
The weird thing is that it happens randomly. So on one device (simulator or real one) it can work fine but at the same time on another one (with the same Apple ID or different) it stops working. After some time on that device it can start working again but maybe on another it stops

The error looks like:

```
LSPrefs: could not find untranslocated node for <FSNode 0x600001faef20> { isDir = ?, path = '/private/var/folders/3d/882v7fpj0hng66chs6crzcqh0000gp/X/0079219F-CF76-5510-AA95-04A31B5E33C0/d/Wrapper/App.app' }, proceeding on the assumption it is not translocated: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"
CGSWindowShmemCreateWithPort failed on port 0
quic_conn_keepalive_handler [C1.1.2.1:2] [-01e8722f12db2367f9e8252e47db312530d9a79d] keep-alive timer fired, exceeding 2 outstanding keep-alives
nw_read_request_report [C1] Receive failed with error "Operation timed out"
nw_read_request_report [C1] Receive failed with error "Operation timed out"
nw_read_request_report [C1] Receive failed with error "Operation timed out"
nw_read_request_report [C1] Receive failed with error "Operation timed out"
0x1231bd418 1 stalled, attempting fallback
Task <037C442C-01E9-4F2E-9E40-53881D4E01C3>.<1> HTTP load failed, 329/0 bytes (error code: 18 446 744 073 709 550 611 [4:18 446 744 073 709 551 612])
nw_endpoint_flow_fillout_data_transfer_snapshot copy_info() returned NULL
Task <037C442C-01E9-4F2E-9E40-53881D4E01C3>.<1> finished with error [18 446 744 073 709 550 611] Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x60000114a9a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x600003c85a90 [0x1e1cc3720]>{length = 16, capacity = 16, bytes = 0x100201bbbc7262ea0000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <037C442C-01E9-4F2E-9E40-53881D4E01C3>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <037C442C-01E9-4F2E-9E40-53881D4E01C3>.<1>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=https://***.supabase.co/auth/v1/token?grant_type=id_token, NSErrorFailingURLKey=https://***.supabase.co/auth/v1/token?grant_type=id_token, _kCFStreamErrorDomainKey=4}
CGSWindowShmemCreateWithPort failed on port 0
```
## To Reproduce

1. Implement [Sign in with Apple](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple) 
2. Retrieve session with `signInWithIdToken(credentials:
                    .init(provider: .apple, idToken: idToken))`
3. Try to launch it on different devices, simulators at different times and wait until the error occurred

Unfortunately there is no clear guideline to reproduce the problem, it is just random
## Expected behavior

The method `signInWithIdToken` shouldn't throw the error

**Comment by grdsdev** [comment]
Hi @Li11leprince does the issue persists?

That error doesn't seem related to the library, is that the only call that fails with that error? What about the other GoTrue methods?

**Comment by hf** [comment]
This indeed looks like a network issue of the device / simulator. A network timeout can be a common error and it's not because of Supabase or the Auth server. Your app should retry the operation whenever possible (such as after getting back online).

I'm not an expert in Apple's ecosystem but this looks a bit weird

```
keep-alive timer fired, exceeding 2 outstanding keep-alives
```

Not sure if anyone from the iOS community can provide more context on whether this is an issue with the configuration of the underlying network primitives.

**Comment by grdsdev** [comment]
I'll be closing this as it doesn't seem to be an issue with the library, if you face the same issue in the future, feel free to re-open it and let me know, thank you!
