### ISSUE TITLE
Add Documentation for Storage

### ISSUE THREAD

**Issue by grdsdev** [supabase-community/supabase-swift#136]

**Comment by samuelOsborne** [comment]
hey @grdsdev in the mean time do you have any docs or examples around for using storage? Just getting started and want to see how hard its going to be. Cheers

**Comment by grdsdev** [comment]
Hey @samuelOsborne , I'm working on this sample app, https://github.com/grdsdev/product-sample-supabase-swift/blob/main/ProductSample/Data/ProductImageStorageRepository.swift 

Is isn't final yet, but you may check it out for example usage of the storage methods.

**Comment by samuelOsborne** [comment]
thanks @grdsdev ! Appreciate it. Im worried though that I wont be able to use Supabase for my iOS project, running in to this error

https://github.com/supabase-community/postgrest-swift/issues/51

**Comment by grdsdev** [comment]
@samuelOsborne I have a fix for that, will push it in the next release.

**Comment by samuelOsborne** [comment]
Awesome thanks @grdsdev. Looking forward to it and being able to use supabase!
