### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by philbaker4** [supabase-community/supabase-swift#14]
Guessing from contribution activity that it's not, but just wanted to check to be sure.. Hoping to use Google SSO in an app Im working on

**Comment by asleepingpanda** [comment]
Same here! I would love to use this in an upcoming project. Any idea how "production ready" it is?

**Comment by grsouza** [comment]
@asleepingpanda and @philbaker4 thanks for asking it.

I'm actively working on this libraries on my fork, seeking for "production readiness". I basically refactored everything, bumped minimum targets to iOS 13 and macOS 10.15 and refactored to async/await only, cause that what make sense to the projects I'll be using this.

Once it's ready I'll try to PR it into the `supabase-community` repos if everyone accepts it.

You can find them in the links below, the `Auth` and `Database` is quite ready, the other ones I'm still working on them, but would be awesome if you could use them and give me some feedback on whats needs to be fixed.

https://github.com/grsouza/supabase-swift
https://github.com/grsouza/gotrue-swift
https://github.com/grsouza/postgrest-swift
https://github.com/grsouza/storage-swift
https://github.com/grsouza/realtime-swift

**Comment by findthebug** [comment]
Same here. Is there any roadmap to deliver a production ready version 1?
