### ISSUE TITLE
[Storage] Add `createSignedUploadURL` and `uploadToSignedURL` method

### ISSUE THREAD

**Issue by grdsdev** [supabase-community/supabase-swift#147]
# Feature request

Add `createSignedUploadURL` and `uploadToSignedURL` method:

- https://github.com/supabase/storage-js/blob/fa44be8156295ba6320ffeff96bdf91016536a46/src/packages/StorageFileApi.ts#L219
- https://github.com/supabase/storage-js/blob/fa44be8156295ba6320ffeff96bdf91016536a46/src/packages/StorageFileApi.ts#L156

**Comment by MadeByDouglas** [comment]
I'm sorry if this is a silly question, what is this feature, the signedUploadURL for? 
Can we get support for resumable uploads and downloads with progress indicators?
https://supabase.com/docs/guides/storage/uploads/resumable-uploads

**Comment by grdsdev** [comment]
Hey @MadeByDouglas those methods are unrelated to resumable uploads.

I added a new issue to track work related to resumable uploads https://github.com/supabase-community/supabase-swift/issues/171

**Comment by MadeByDouglas** [comment]
ah ok I see, awesome!
Also great work btw, I've seen lots of progress with this recently. Have you taken over the project from maail or connected with supabase or just contributing?
I'm very thankful for all the work on this library from you and the others.

**Comment by ehynds** [comment]
Would love to see progress on this!

**Comment by grdsdev** [comment]
Hi @ehynds I'm joining Supabase to work full time on next week, so expect this to move forward much faster.

Thanks.
