### ISSUE TITLE
README refers to SupaBaseAuth which doesn't exist

### ISSUE THREAD

**Issue by kchro3** [supabase-community/supabase-swift#151]
# Bug report

README says to use SupaBaseAuth for deeplinking, which is not in this library. Looks like a typo?

## To Reproduce

N/A

## Expected behavior

N/A

## Screenshots

N/A

## System information
N/A
## Additional context

N/A

**Comment by grdsdev** [comment]
Hey @kchro3 README is outdated, I'll be fixing it shortly, thanks for opening this.
