### ISSUE TITLE
How do you use client.auth.authEventChange?

### ISSUE THREAD

**Issue by samuelOsborne** [supabase-community/supabase-swift#152]
# Improve documentation

## Link 

https://github.com/supabase-community/supabase-swift

## Describe the problem

Missing inside of Readme

## Describe the improvement

Please add an explanation on how to check for auth using onAuthEventChange:

```
self.client = SupabaseClient(..)

client.auth.authEventchange ... 
```

Also, is there a way on the client to check users state, is signed in?

## Additional context

Was going through your repo you shared @grdsdev https://github.com/grdsdev/product-sample-supabase-swift/blob/main/ProductSample/Data/AuthenticationRepository.swift

Would it be ok to use the auth code in that app in a production app? 

I saw the  code you had was a bit different in terms of API usage:

onAuthStateChange instead of authEventChange. In my project it can't find authStateChange on the Supabase client

```
    await client.onAuthStateChange().compactMap ...

```

**Comment by grdsdev** [comment]
Hey @samuelOsborne README is still outdated, I'll fix it shortly.

The product sample you linked uses the version that will become the v1 release so you can follow that for now.

**Comment by lukaskf** [comment]
@grdsdev I'm confused here as well. Looks like this repo is going through a lot of changes, which is great to see! But that sample project linked above throws a 404. 

I'm following[ this one ](https://github.com/supabase-community/supabase-swift/blob/main/Examples/Examples/AuthView.swift), but in XCode I get the following error:

Value of type 'GoTrueClient' has no member 'onAuthStateChange'

Is `authEventChange` replacing `onAuthEventChange`?

**Comment by lukaskf** [comment]
I think I just figured it out. I was on `0.3.0` had force xcode to use `main` branch. 

So `onAuthEventChange` is for the latest version (`1.0`) to be released. And the sample projects _are_ up to date.

**Comment by samuelOsborne** [comment]
yep @lukaskf the documentation on the supabase website for swift is for v1.0 too
