### ISSUE TITLE
Realtime subscription always timedOut

### ISSUE THREAD

**Issue by w0wka91** [supabase-community/supabase-swift#165]
# Bug report

When I follow the documentation to subscribe to a channel and listen for all database changes, I always get a timed out response.

## To Reproduce

```swift
let supabase = SupabaseClient(
    supabaseURL: Secrets.supabaseURL,
    supabaseKey: Secrets.supabaseAnonKey
)

let channel = socket
  .channel("room1")
  .on("postgres_changes", filter: ChannelFilter(event: "*", schema: "public", table: "table_name")) { message in
    print("Change received!", message.payload)
  }
  channel.onError { message in
      print(message)
  }
  channel.subscribe(timeout: 2) { state, e in
      print(state)
      print(e)
  }
```

I can get it working if I do it the way you did it in the examples folder:

```swift
let socket: RealtimeClient = {
  let client = RealtimeClient(
    "https://supabase_id.supabase.co/realtime/v1",
    params: [
        "apikey": Secrets.supabaseAnonKey,
    ]
  )
  client.logger = { print($0) }
  return client
}()

let channel = socket
  .channel("room1")
  .on("postgres_changes", filter: ChannelFilter(event: "*", schema: "public", table: "table_name")) { message in
    print("Change received!", message.payload)
  }
channel.onError { message in
    print(message)
}

channel.subscribe(timeout: 2) { state, e in
    print(state)
    print(e)
}
```

Not sure if this is a documentation issue or a bug.

**Comment by hexlogic** [comment]
Same here

**Comment by grdsdev** [comment]
Hey @w0wka91,

Let me see If I understood it correctly, it works when you use `RealtimeClient` directly but doesn't when you use it through the `SupabaseClient`?

**Comment by w0wka91** [comment]
Hey @grdsdev . Yes, thats correct. Not sure if the `RealtimeClient`through the `SupabaseClient`is configured differently

**Comment by grdsdev** [comment]
Go it, will check it out.

Thank you!

**Comment by grdsdev** [comment]
@w0wka91 I made a few changes to the example, check it out https://github.com/supabase-community/supabase-swift/pull/167

And make sure you're calling `supabase.realtime.connect()`.

If you still have issues, paste Realtime logs here.

**Comment by adhanson6** [comment]
Was anyone able to get this working? I am running into the same issue I believe.

**Comment by grdsdev** [comment]
@adhanson6 in your logs you are getting a `status code: 403` response, there is probably something wrong with your Supabase project, can you verify if realtime is enabled for the project and table you're trying to listen to?

This is the doc on how to do it https://supabase.com/docs/guides/realtime/postgres-changes#replication-setup

**Comment by adhanson6** [comment]
@grdsdev I have verified that realtime is enabled for my table in the replications section under supabase_realtime. I also added the RLS policy on that linked page to allow anon access to reading my table, as well as public access for all operations on my table but am still receiving the same error. Is there another place that realtime needs to be enabled other than that replications section?

**Comment by w0wka91** [comment]
@grdsdev Thanks for fixing. It works for me now
