### ISSUE TITLE
[Request] When are docs for Realtime and Storage coming?

### ISSUE THREAD

**Issue by chFlorian** [supabase-community/supabase-swift#17]
I played around with Realtime based on the realtime-swift docs, but I just couldn't get it to work.
It would be great if you added docs for both of those features, since it has been months since anything changed with them.

**Comment by grsouza** [comment]
This https://github.com/supabase-community/realtime-swift/pull/5 may solve your issue with the Realtime not working, if that's the case try testing again with the latest version of this library.
