### ISSUE TITLE
Provide initial user data via third-party login

### ISSUE THREAD

**Issue by junjielu** [supabase-community/supabase-swift#183]
# Feature request

## Is your feature request related to a problem? Please describe.

The current `signInWithIdToken` method is unable to pass in some metadata to populate the initial user data.

As an example, I would like to pass in the account creation time `created_at` during registration, and use a trigger to insert the data into the profiles table.

## Describe the solution you'd like

Like the `signUp` method, provide parameters for passing in metadata

## Additional context

https://github.com/orgs/supabase/discussions/3491

**Comment by grdsdev** [comment]
Hi @junjielu I don't think that is possible, the signInWithIdToken doesn't support a metadata parameter.

Looking at js library it doesn't support this either: https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L554

About the thing you're trying to accomplish, why do you need to pass the `created_at` from the client? Can't your trigger insert a `created_at` into your profile table? 

The `auth.users` schema has a lot of information you can use to populate the profile schema on sign-up.

**Comment by junjielu** [comment]
@grdsdev Thank you for your reply. I understand that supabase really doesn't do what I'm talking about, but I don't think that makes a lot of sense.

Passing in some metadata during the user registration phase is a very reasonable thing to do, such as user nicknames and user avatars. Due to the special nature of oauth login, login and registration use the same interface, which results in these metadata not being populated on insertion into the table, but only lagged after login is complete, which I don't think is a good implementation.

Currently it seems that I can only update the data in the table after the user has registered via `PostgrestClient`, which achieves the same result, but if the update fails then there is a risk of data loss.

**Comment by grdsdev** [comment]
You can use `update(user:)` method for updating metadata post login https://github.com/supabase-community/supabase-swift/blob/main/Sources/GoTrue/GoTrueClient.swift#L721

I think you should open a new discussion on https://github.com/orgs/supabase/discussions about this.

**Comment by junjielu** [comment]
You're right, I think this should be the underlying implementation part
