### ISSUE TITLE
[Auth] Add support for delete user

### ISSUE THREAD

**Issue by MadeByDouglas** [supabase-community/supabase-swift#192]
# Feature request
Match the javascript library and allow swift to delete a user without needing a postgres or edge function

## Is your feature request related to a problem? Please describe.
Apple requires apps with social features to allow users to delete their own profiles and data from the app, so this should be in the swift library so it can be easily implemented.

## Describe the solution you'd like
match the javascript client https://supabase.com/docs/reference/javascript/auth-admin-deleteuser
They note this should only be done on the server, not on the web browser as not to expose `service-role` key, would this be a dealbreaker for swift as well or can it be done since its compiled?

## Describe alternatives you've considered
using postgres or edge functions

**Comment by grdsdev** [comment]
Thank you for bringing this up @MadeByDouglas, I plan to add the Admin APIs soon and will start with this one since you need it.

**Comment by MadeByDouglas** [comment]
ok sweet, yeah I am currently using rpc but it seems this would be great to have in the swift library

**Comment by mypalvikram** [comment]
Hey 👋🏽, is this still being worked on?

**Comment by grdsdev** [comment]
Sorry for the delay, but I just started working on this, check progress in #224

**Comment by grdsdev** [comment]
Released: https://github.com/supabase-community/supabase-swift/releases/tag/2.3.0

**Comment by MadeByDouglas** [comment]
awesome! thanks so much

**Comment by grdsdev** [comment]
@MadeByDouglas tho this is now possible, be careful as to not expose the `service_role` key.

You can check this on ways to keep it safe https://nshipster.com/secrets/
