### ISSUE TITLE
[Auth] Implement identity linking

### ISSUE THREAD

**Issue by grdsdev** [supabase-community/supabase-swift#193]
# Feature request

## Is your feature request related to a problem? Please describe.

Implement new identity linking feature: https://supabase.com/docs/reference/javascript/auth-getuseridentities

**Comment by johndpope** [comment]
already implemented for kotlin - https://supabase.com/docs/reference/kotlin/auth-linkidentity

**Comment by johndpope** [comment]
Thanks @grdsdev  - 
you gotta jump onto claude ai - 
I'm cranking out AI code by prompt engineering.

https://github.com/johndpope/MusicControlNet
https://github.com/johndpope/emote-hack
