### ISSUE TITLE
[Realtime] Auto-reconnect does not rejoin channels

### ISSUE THREAD

**Issue by TiagoLira** [supabase-community/supabase-swift#196]
# Bug report

## Describe the bug

When the socket disconnects with an error (no internet, for example), it correctly starts a reconnection timer.
When the client manages to reconnect, the channel is not receiving updates anymore, but is still marked as "joined"

Trying to rejoin the channel causes a fatal error ("channel must be joined only once"). Removing the channel on disconnect stops the timer altogether.
I managed to workaround it by creating a new channel first, on reconnect, and then removing the old channel. 
But this doesn't seem like intended behaviour so decided to send a report. Apologies if this is already being addressed elsewhere.

## To Reproduce

When listening to database changes in a realtime channel, the issue can be quickly reproduced by setting the phone to airplane mode, let the client disconnect, and then restoring the internet connection.

## Expected behavior

When internet connection is restored and the client reconnects, channels should start receiving updates again.

## System information

- OS: iOS 17.2
- Version of supabase-swift: 1.0.0

**Comment by grdsdev** [comment]
Thanks Tiago for opening this issue, I'll investigate it and try to have a fix for it.

**Comment by grdsdev** [comment]
This is fixed on the latest `RealtimeV2` client, please use RealtimeV2 as it will become the standard on upcoming releases.
