### ISSUE TITLE
Storage schema always returning empty?

### ISSUE THREAD

**Issue by samuelOsborne** [supabase-community/supabase-swift#197]
# Bug report

## Describe the bug

When using the Storage schema and accessing the objects table (I just need the name), it always returns an empty array.

## To Reproduce

Create a client with the 'storage' schema set :

```Swift
        let storageClient = SupabaseClient(supabaseURL: URL(string: "...")!, supabaseKey: "...", options: SupabaseClientOptions(db: SupabaseClientOptions.DatabaseOptions(schema: "storage")))
```

Try and query some data:

```Swift
struct Storage: Encodable, Decodable {
//    var id: UUID?
//    var bucketID: String?
    var name: String?
//    var owner: UUID?
//    var createdAt: Date?
//    var updatedAt: Date?
//    var lastAccessedAt: Date?
//    var metadata: [String: String]? // Assuming a dictionary to represent JSONB data
//    var pathTokens: [String]? // Assuming an array of strings for path tokens
//    var version: String?
//    var ownerID: String?
}

let storageFile: [Storage] = try await storageClient.database
    .from("objects")
    .execute().value

print(storageFile)
```

## Expected behavior

Should return the whole objects table.

## Additional context

Personally just need the "name" column data. I think using the objects table is better than saving the path to files inside supabase storage myself (duplicate data)?

**Comment by grdsdev** [comment]
Hi @samuelOsborne 

I made a few tests and it worked as expected, and I could query the storage schema.

Make sure the `storage.objects` table has RLS correctly defined allowing access, if that still doesn't work for you, let me know.

**Comment by grdsdev** [comment]
Added a PR for allowing to switch schema and improving this a bit, https://github.com/supabase-community/supabase-swift/pull/199

**Comment by samuelOsborne** [comment]
Thanks @grdsdev still trying to get my head around policies but its working. That PR looks great, cheers!
