### ISSUE TITLE
Supabase installation doesn't work

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#20]
I've followed steps to install Supabase but Xcode(v13.1) unable to import Supabase for an iOS app

How I installed?
SPM - Search by URL and then added the package successfully

Debugging:
Tried
- Clean Build folder
- Restart Xcode

Actual result:
- Unable to import it 
![CleanShot 2022-03-16 at 17 24 13@2x](https://user-images.githubusercontent.com/6823101/158584420-757ebf54-1958-49ed-9366-ac48f8bb4c71.png)

**Comment by grsouza** [comment]
@pradeepb28 thanks for reaching out with your issue, sorry for the inconvenience.

Can you test using the latest version [[0.0.3](https://github.com/supabase-community/supabase-swift/releases/tag/0.0.3)] **it should be fixed now**.

**Comment by Vaibhav-214** [comment]
It is not working, even though I can see the Supabase api's in autocomplete the import is giving error

![Screenshot 2024-02-05 at 7 11 12 PM](https://github.com/supabase-community/supabase-swift/assets/94449143/d1df0c7e-d707-4abd-a1e7-24517ef491cd)
