### ISSUE TITLE
Fatal error when using sign up and sign in

### ISSUE THREAD

**Issue by mhaezaragoza** [supabase-community/supabase-swift#21]
Hi, I'm experiencing a fatal error when using client.auth.signIn and client.auth.signUp

<img width="1236" alt="Screen Shot 2022-03-27 at 7 19 11 PM" src="https://user-images.githubusercontent.com/62824325/160279187-c0c766ff-5caa-4252-b56c-4713c38a044d.png">

Here is my code

<img width="693" alt="Screen Shot 2022-03-27 at 7 19 45 PM" src="https://user-images.githubusercontent.com/62824325/160279211-7ad53140-8a6e-4068-8f4c-3e944c73e7b5.png">

Hope you can help me.

**Comment by grsouza** [comment]
Thanks for reporting this.

As a quick fix you can store the `client` as a property in the `ViewController`, that way you make sure that the client is live until the request comes back.

**Comment by grsouza** [comment]
The latest version [0.0.4](https://github.com/supabase-community/supabase-swift/releases/tag/0.0.4) should fix this.

**Comment by mhaezaragoza** [comment]
Thanks @grsouza! It is now working using 0.0.4.
