### ISSUE TITLE
[Auth] Implement captchaToken for signInWithPassword

### ISSUE THREAD

**Issue by cwjoshuak** [supabase-community/supabase-swift#210]
# Feature request
signInWithPassword (both email and phone) is missing the optional `captchaToken` field
https://github.com/supabase/gotrue-js/blob/b664f0f4f22151434ec5be3240465b6b96ffeaaa/src/GoTrueClient.ts#L465

## Is your feature request related to a problem? Please describe.
These methods are missing the captchaToken field, which gets encoded in the body with `gotrueMetaSecurity`

## Describe the solution you'd like
I would like to be able to provide an optional captcha token to the methods.

**Comment by MuhtasimTanmoy** [comment]
Would like to work on it.

**Comment by grdsdev** [comment]
Hi @MuhtasimTanmoy feel free to take it.

Just try to follow the same pattern as the other methods.

Then open a PR and I'll be glad reviewing it.

If you need any help, let me know.
