### ISSUE TITLE
Is this bug related to SDK or Supabase backend?

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#215]
When I try to create new user accounts using "signInWithOTP" method it throws error consistently.
(FYI, no issues with login - it is just with sign up)

I've reached out to Supabase team but no reply yet.

<img width="922" alt="CleanShot 2024-01-03 at 11 50 19@2x" src="https://github.com/supabase-community/supabase-swift/assets/6823101/eca75c7d-88e4-4a3c-924a-7b56e642c0fb">

<img width="1190" alt="CleanShot 2024-01-03 at 11 50 07@2x" src="https://github.com/supabase-community/supabase-swift/assets/6823101/4a964edd-856e-4408-a171-afa4bee23bae">

<img width="424" alt="CleanShot 2024-01-03 at 12 01 52@2x" src="https://github.com/supabase-community/supabase-swift/assets/6823101/e1ae8719-02a4-483a-a522-6525b23276fc">

**Comment by grdsdev** [comment]
Hi @pradeepb28 

Do you have any trigger running on sign up? It seems like it is throwing an error due a missing cid field on the new record

**Comment by pradeepb28** [comment]
Thanks for confirming, I have added a trigger but it seems like it saying there is no table users when I use

Drop trigger on_credits_insert on users; (FYI, users is auto-generated table from Supabase based on the user authentication I think)

<img width="912" alt="CleanShot 2024-01-03 at 14 28 55@2x" src="https://github.com/supabase-community/supabase-swift/assets/6823101/c77c93d5-f33b-4080-8dee-e886dfd3f79b">
