### ISSUE TITLE
Calling update with explicit nil value should set the value to NULL 

### ISSUE THREAD

**Issue by Magnuti** [supabase-community/supabase-swift#217]
If I have a user in my database with both name and age set to some value (i.e., not `NULL`) then calling this will update name to `NULL`.

```swift
let updateData: [String: String?] = ["name": nil]
                
try await supabaseClient.database
    .from("user_info")
    .update(updateData)
    .execute()
```

But calling this will only update age.

```swift
struct UpdateDTO: Encodable {
    let name: String?
    let age: Int?
}

try await supabaseClient.database
    .from("user_info")
    .update(UpdateDto(name: nil, age: 20))
    .execute()
```

When explicitly passing `name: nil` the value should be set to `NULL`, not omitted.

**Comment by grdsdev** [comment]
Hi @Magnuti thanks for opening the issue.

This isn't a bug in the SDK, it is just how auto-synthesized Encodable works, it omits `null` values by default.

The `UpdateDto(name: nil, age: 20)` gets encoded as:

```json
{
    "age": 20
}
```

To walk through this default behavior, you have to add a custom implementation to the `UpdateDto` model, such as:

```swift
struct UpdateDTO: Encodable {
  let name: String?
  let age: Int?

  enum CodingKeys: String, CodingKey {
    case name
    case age
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(name, forKey: .name) // encode Optional<String>
    try container.encode(age, forKey: .age) // encode Optional<Int>
  }
}
```

Another option is to use the `AnyJSON` type:

```swift
try await supabaseClient.database
    .from("user_info")
    .update(AnyJSON.object(["name": nil, "age": 20]))
    .execute()
```

If you still have doubts regarding this, please let me know.

**Comment by Magnuti** [comment]
Thank you for the explanation! I'll try it out

**Comment by Magnuti** [comment]
The first approach with custom `CodingKeys` worked well! It looks like the latter with `AnyJSON` works for string values only.

**Comment by grdsdev** [comment]
Thank you @Magnuti I'll check what you said about the `AnyJSON` not working as expected.
