### ISSUE TITLE
Crash on SupabaseStorageClient.from()

### ISSUE THREAD

**Issue by kevlust** [supabase-community/supabase-swift#229]
# Bug report

## Describe the bug

I've noticed numerous crashes on my app coming from `SupabaseStorageClient.from(_:)`. At worst, this function should probably fail silently.

## To Reproduce

I'm not sure how to reproduce this issue. It only happens occasionally (when trying to download photo files from Supabase storage).

## Expected behavior

No crash :)

## System information

- iOS: 17.2.1
- iPhone 14 Pro
- Supabase package version: 2.1.0

## Additional context

Stack trace of the crash:

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x3a68fc _swift_release_dealloc + 32
1  libswiftCore.dylib             0x3a7fb0 bool swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::doDecrementSlow<(swift::PerformDeinit)1>(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 136
2  Unspoken                       0xeb935c SupabaseStorageClient.from(_:) + 30 (SupabaseStorage.swift:30)
3  Unspoken                       0xd23d0c StorageService.downloadProfilePicture(forUserWithID:) + 30 (StorageService.swift:30)
4  libswift_Concurrency.dylib     0x41ac4 swift::runJobInEstablishedExecutorContext(swift::Job*) + 436
5  libswift_Concurrency.dylib     0x42d54 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
6  libdispatch.dylib              0x15be4 _dispatch_root_queue_drain + 392
7  libdispatch.dylib              0x163ec _dispatch_worker_thread2 + 156
8  libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

Code snippet that's crashing:
```
let data = try await supabaseClient
    .storage
    .from("my_bucket_name") // This line is crashing according to Firebase logs
    .download(path: filePath)
```

**Comment by grdsdev** [comment]
Hi @kevlust, thanks for opening this issue, but unfortunately this is a bit difficult to track.

Can you provide a sample project that crashes?

**Comment by kevlust** [comment]
Hi @grdsdev, thanks for the quick reply!

Unfortunately, I'm not allowed to share code from the project that is crashing. I'm not sure I'd be able to create a sample project that crashes since this only crashes very very occasionally, and I wouldn't be able to tell if the sample project triggers that crash too. I've tried to reproduce it for hours with no luck. I just know that, every few days, there's a new crash with that same stack trace.

Is there anything that gets called as a consequence of that `from()` line that could be causing this crash? Happy to get on a call with the team or help in any way. Please let me know!

**Comment by grdsdev** [comment]
I understand.

The `from` method initializes a `StorageFileApi` object and returns it, that object is then used for calling the `download` method.

Do you know if the crash happens before or after the download of the file?

**Comment by grdsdev** [comment]
Closing due to lack of response back.

Feel free to re-open it if you're still facing this issue.

Thanks!
