### ISSUE TITLE
SupabaseLogger in swift Missing return in getter

### ISSUE THREAD

**Issue by AndradeDaniel99** [supabase-community/supabase-swift#231]
# Bug report

## Describe the bug

Cant build my project after import supabase because supabaseLogger throws an error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Just import supabase into a new project
2. build

## Expected behavior

Not throw an error.

## Screenshots

<img width="1024" alt="Screenshot 2024-02-03 at 18 30 46" src="https://github.com/supabase-community/supabase-swift/assets/3867413/969516dd-09e3-46b8-927e-cc6e0fdf3e8e">

## System information

- OS: MacOS Ventura 13.4
- Version of supabase-swift: 2.3.0

## Aditional context

Maybe this works: 
<img width="463" alt="Screenshot 2024-02-03 at 18 35 08" src="https://github.com/supabase-community/supabase-swift/assets/3867413/dd4e836f-9967-4927-8212-c539f3c95ed5">

**Comment by ilaffey2** [comment]
Also seeing this- first time using supabase-swift after coming from JS. Pretty dissapointing

**Comment by grdsdev** [comment]
Hi all.

That code should work if you use latest Swift 5.9, please use that version if you can.

I'll also fix that so it builds for Swift 5.8 too.

Thanks for opening this issue.

**Comment by grdsdev** [comment]
Fixed on [2.3.1](https://github.com/supabase-community/supabase-swift/releases/tag/2.3.1)
