### ISSUE TITLE
Supabase Installation is not working

### ISSUE THREAD

**Issue by Vaibhav-214** [supabase-community/supabase-swift#236]
# Bug report

## Describe the bug
import statements are not recognised

I have added the supabase sdk using swift package manager and I can see the supabase api's in autocomplete but the autocomplete doesn't shows Supabase module when i try to import it
Also when I try to run it , I get this

![Screenshot 2024-02-05 at 7 11 12 PM](https://github.com/supabase-community/supabase-swift/assets/94449143/d1df0c7e-d707-4abd-a1e7-24517ef491cd)

## To Reproduce

1.Create a new ios project
2.add supabase sdk using package manager, I m using version 2.0.0
3.try to use the "import Supabase"
4.try to run the app

## System information

- OS: [e.g. macOS]
- Version of supabase-swift: [2.3.1]

## Additional context
This is similar to issue #20

**Comment by grdsdev** [comment]
Hi @Vaibhav-214 please, make sure you also added the `Supabase` target to your project as a dependency, not only added the `supabase-swift` package.

This is probably an error with your project configuration, try following the examples we have at https://github.com/supabase-community/supabase-swift/tree/main/Examples

If you still have issues after that, please let me know.

**Comment by Vaibhav-214** [comment]
Thanks, it worked.I am an android developer so not familiar with xcode and swift development
