### ISSUE TITLE
Apple sign in: BAD ID TOKEN

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#238]
We're seeing sometimes constantly and sometimes sporadically when attempting to sign in or sign up using Apple

```
▿ GoTrue.GoTrueError.api
  ▿ api: GoTrue.GoTrueError.APIError
    - message: nil
    - msg: nil
    - code: nil
    ▿ error: Optional("invalid request")
      - some: "invalid request"
    ▿ errorDescription: Optional("Bad ID token")
      - some: "Bad ID token"
```

SDK version: master
![CleanShot 2024-02-07 at 12 40 27@2x](https://github.com/supabase-community/supabase-swift/assets/6823101/8a24853f-8833-40c2-8415-9f7f4f33b295)

**Comment by grdsdev** [comment]
Hi @pradeepb28 that error is thrown from the GoTrue server, as long as you're sending the correct values in the request, there is not much we can do on the client.

- Can you double-check you're sending the correct `id_token` and `access_token` on the request?
- Also, can you check the project is correctly configured? Make sure you follow the docs: https://supabase.com/docs/guides/auth/social-login/auth-apple?platform=swift

Let me know what the results are, I'll gladly help you further.

**Comment by grdsdev** [comment]
Got it @pradeepb28 I'll check with the backend team to see if they know of any change on their side that could impact this.
