### ISSUE TITLE
"No such module" since moving from official github org

### ISSUE THREAD

**Issue by louis030195** [supabase-community/supabase-swift#244]
i used to use supabase swift from official github org:
![image](https://github.com/supabase-community/supabase-swift/assets/25003283/369ca91f-7819-45c4-8483-7e1cfd20e987)

but is seems to have moved:
![image](https://github.com/supabase-community/supabase-swift/assets/25003283/0d726965-ab03-4b6e-a388-f52572c8619d)

now it stopped working "No such module"
![image](https://github.com/supabase-community/supabase-swift/assets/25003283/d61449f5-ae85-4f0f-b4fa-eed04c828f6f)

I use Xcode (unfortunately lol, such an awful IDE)

Any idea how to fix this? I tried to remove and re-add the repo through Xcode clicks like in the docs without improvement.

Thanks 🙏

**Comment by louis030195** [comment]
![image](https://github.com/supabase-community/supabase-swift/assets/25003283/e9d8dfa0-6c6f-4b17-931a-5776be1cd8d5)

**Comment by grdsdev** [comment]
Hey @louis030195 

Can you make sure the Supabase is added to the proper targets?

On here:
![image](https://github.com/supabase-community/supabase-swift/assets/5923044/b2b67434-fc44-4921-9195-85c56a9e4f9f)

**Comment by louis030195** [comment]
Hmm thanks @grdsdev , Supabase was missing in Targets, really hard to use IDE. Do you have any suggestion on how to switch to Swift Package Manager? Ideally I do not use Xcode at all and only Cursor and CLI

**Comment by grdsdev** [comment]
Hey, you can try VS Code with the Swift extension, that works great for building Swift Packages, but won't work for Applications.

I'd suggest you get to know Xcode better, it is far from being the best IDE, but it gets the work done once you get used to it.

If you need further assistance, please let me know.

Thanks.

**Comment by phgn0** [comment]
FYI I just wanted to import the `Auth` module, but turns out you also need the `Supabase` one, which appears only after scrolling down in XCode.

![Image](https://github.com/user-attachments/assets/7e11e1bd-df2e-43d1-8706-d7b606c63b2c)
