### ISSUE TITLE
Swift: Missing package product 'GoTrue'

### ISSUE THREAD

**Issue by marcusraty** [supabase-community/supabase-swift#249]
# Bug report

## Describe the bug

I was previously using commit 5382411, but updating to the latest today I get the error Missing package product 'GoTrue'

Any assistance would be appreciate I do not understand what has changed - nothing else but the latest version of supabase swift client on my end.

**Comment by grdsdev** [comment]
Hi @marcusraty 

GoTrue got renamed to Auth a couple of releases ago, please just swap `import GoTrue` to `import Auth`.

Thanks.

**Comment by marcusraty** [comment]
Sorry for the slow reply. The issue was (I am using the swift package in Xcode for iOS) I still had GoTrue in the Frameworks, Libraries and Embedded Content. Thanks for your help again, excited to see so much active work on the swift client!👏
