### ISSUE TITLE
Could not prevent man-in-the-middle using a Info.plist based SSL Certificate Pinning on watchOS 

### ISSUE THREAD

**Issue by henriquestiagoo** [supabase-community/supabase-swift#258]
# Bug report

I want to prevent snooping and man-in-the-middle attacks to my supabase database. Apple introduced native support for SSL public key pinning in iOS 14. You just need to specify a collection of certificates in your Info.plist that App Transport Security (ATS) expects when connecting to named domains.

For that, I have calculated my SPKI-SHA256-BASE64 from my supabase SSL certificate. 

I am following this Info.plist based cert pinning approach on watchOS but it is not working ..

This is my Info.plist source code:

<img width="488" alt="supabase-ios-info" src="https://github.com/supabase-community/supabase-swift/assets/17295803/47bf18cf-e17c-4947-9ca8-15a9b64971e3">

## Describe the bug

According to the documentation, this built-in pinning works well for URLSession, but I am using Proxyman and I can snoop all my network requests. I expected to receive a SSL error because a secure connection to the server could not be made.

## Expected behavior

I expected to receive a SSL error because a secure connection to the server could not be made.

## System information

- OS: watchOS 10.3.1
- Version of supabase-swift: 2.3.1

## References

- [Identity Pinning: How to configure server certificates for your app](https://developer.apple.com/news/?id=g9ejcf8y)
- [Info.plist based Certificate Pinning on iOS](https://blog.eidinger.info/infoplist-based-certificate-pinning-on-ios)

**Comment by tiago-d-henriques** [comment]
Ok, NSAppTransportSecurity is not available on watchOS ...

Do you know if I can implement SSL pinning on watchOS somehow ?

- [NSAppTransportSecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity)

**Comment by henriquestiagoo** [comment]
I get it working by creating a URLSession pinning delegate and making sure the public key hash from the certificate is valid.

**Comment by grdsdev** [comment]
Hi @henriquestiagoo 

I'd suggest you try to pass the custom `URLSession`, glad you found a way and it worked.

**Comment by henriquestiagoo** [comment]
Hi @grdsdev,

Thank you for your reply!

That is what I am doing :) the custom URLSession contains a pinning delegate to valid the server.
