### ISSUE TITLE
Debugging: How to see returned json or similar

### ISSUE THREAD

**Issue by paul-brenner** [supabase-community/supabase-swift#277]
# Improve documentation

## Describe the problem

I am using supabase-swift primarily by wrapping my queries in functions that return the correct object and letting supabase-swift do it's magic to automatically parse the response into an object, just like in [this example](https://github.com/supabase-community/supabase-swift/blob/363aa00d33699ce5b60686049cabff8508389ab9/Examples/SlackClone/MessageStore.swift#L178)  

```swift
  private func fetchMessages(_ channelId: Channel.ID) async throws -> [Message] {
    try await supabase.database
      .from("messages")
      .select("*,user:user_id(*),channel:channel_id(*)")
      .eq("channel_id", value: channelId)
      .order("inserted_at", ascending: true)
      .execute()
      .value
  }
``` 

But when my select queries get especially complex (usually because of joins) I find it hard to debug the output so that I can properly adjust either my query or the object definition. Is there a good way to just print the resulting json? Or is there some other smarter way I can look at what the supabase.database.etc is returning so I can do this debugging?

## Describe the improvement

I suspect I may not be the only one who would benefit from an example either in the documentation or in an example function?

**Comment by grdsdev** [comment]
Hi @paul-brenner thanks for pointing out this improvement.

I made a few changes related to this on the latest `main` branch but it wasn't released yet.

Changes was:
* Lib now logs the request/response body as in https://github.com/supabase-community/supabase-swift/blob/main/Sources/_Helpers/Request.swift#L49

And, then you can attach a logger implementation when initializing the `SupabaseClient` to have access to the logs, such as:

```swift
let client = SupabaseClient(
  supabaseURL: ...,
  supabaseKey: ...,
  options: .init(
    global: .init(
      logger: ConsoleLogger()
    )
  )
)

struct ConsoleLogger: SupabaseLogger {
  func log(message: SupabaseLogMessage) {
    print(message.description)
  }
}
```

The simplest implementation is just to print out the message, but you can inspect the message to filter out things you don't care about.

The above hasn't been released yet.

Expect a release this week with updated documentation.

Thanks.

**Comment by paul-brenner** [comment]
This is already immediately helpful. Thanks!
I'll keep an eye out for updated documentation, I'm interested in what ways this could be used in addition to just dumping every message to console.
