### ISSUE TITLE
Realtime subscriptions don't work

### ISSUE THREAD

**Issue by ooolzhas** [supabase-community/supabase-swift#36]
Socket is connected, channel is seemingly subscribed (it fires on "receive 'ok'")

It never fires on ".all" or any other events

Only when I unsubscribe "onClose" actually fires ("onError" never fires)

Replication is enabled on all tables, it doesn't work even on non-RLS tables

In API and Postgres logs I could only see "websocket" connections, didn't see any "subscription" logs if there are supposed to be any

@grsouza please help

I'm setting it up like Realtime Swift docs say

**Comment by ooolzhas** [comment]
UPD: channel doesn't subscribe, no subscriptions found in realtime:subscriptions in the dashboard

Found related commits from Realtime JS:

[fix: add RealtimeChannel](https://github.com/supabase/realtime-js/commit/ead7a93ad2aad9cde9badfae360b97163c8a568a) — March 30
[fix: update RealtimeClient to support RealtimeChannel](https://github.com/supabase/realtime-js/commit/8b797247fc253e0fd8cf390307ffe9e6aad0e475) — March 30

Could this be it?

**Comment by ooolzhas** [comment]
My theory:

```
self.trigger(event: ChannelEvent.channelReply(message.ref),
                         payload: message.payload,
                         ref: message.ref,
                         joinRef: message.joinRef)
```

Is missing from

```
private func on(_ event: ChannelEvent, delegated: Delegated<Message, Void>) -> Int {
        let ref = bindingRef
        bindingRef = ref + 1

        bindingsDel.append(Binding(event: event, ref: ref, callback: delegated))
        return ref
    }
```

But I'm not sure, that's my understanding after a few hours of inspection

**Comment by ooolzhas** [comment]
@grsouza I triangulated the error

"message.status" returns nil when you're listening to ".all / .insert / .update / .delete", because the payload doesn't contain "status" and "message.status" is an optional String

Somewhere in the code there's a guard statement that returns if "message.status" is nil

If I use "onMessage" I am able to successfully receive the message & the payload, and from there I retrieve the event type

I'm not creating a PR because I'm too clumsy and don't know how to fix this myself

**Comment by jenspots** [comment]
@ooolzhas you seem to be on the right track. After quite a bit of debugging I was simply able to switch `.on(.message)` to `.onMessage` thanks to your comments above. You surely saved me a lot of time.

**Comment by ooolzhas** [comment]
@jenspots Glad to hear it helped

**Comment by wweevv-johndpope** [comment]
close this
