### ISSUE TITLE
consider supporting xcframworks

### ISSUE THREAD

**Issue by johndpope** [supabase-community/supabase-swift#38]
had some success spitting this out

https://github.com/mstfy/spm-to-xcframework

/Users/johndpope/Desktop/spm-to-xcframework/.build/arm64-apple-macosx/release/spm-to-xcframework Sup
abase --path /Users/johndpope/Desktop/supabase-swift --output /Users/johndpope/Desktop/xcframework

![Screen Shot 2022-08-31 at 11 23 17 am](https://user-images.githubusercontent.com/289994/187572239-17910d34-bb38-4c40-90af-f81fb0c714b5.png)

it's helpful for bazel builds

**Comment by johndpope** [comment]
Sorry - bumping into several issues here

this library 
https://github.com/unsignedapps/swift-create-xcframework

```shell
brew install mint
mint install unsignedapps/swift-create-xcframework
swift create-xcframework --platform ios
```

I need a path to get this working - 
the realtime has an issue with zlib

spleeter) ➜  supabase-swift git:(master) ✗ swift create-xcframework --platform ios
Error: Xcode project generation is not supported by Swift Package Manager for packages that reference system modules.These system modules were referenced: **swift-nio-zlib-support**


```bazel

// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
  name: "Supabase",
  platforms: [
    .iOS(.v13),
    .macCatalyst(.v13),
    .macOS(.v10_15),
    .watchOS(.v6),
    .tvOS(.v13),
  ],
  products: [
    .library(
      name: "Supabase",
      targets: ["Supabase"]
    )
  ],
  dependencies: [
    .package(url: "https://github.com/supabase-community/gotrue-swift", from: "0.0.7"),
    .package(url: "https://github.com/supabase-community/storage-swift.git", from: "0.0.2"),
    .package(url: "https://github.com/supabase-community/postgrest-swift", from: "0.0.6"),
  ],
  targets: [
    .target(
      name: "Supabase",
      dependencies: [
        .product(name: "GoTrue", package: "gotrue-swift"),
        .product(name: "SupabaseStorage", package: "storage-swift"),
        .product(name: "PostgREST", package: "postgrest-swift"),
      ]
    )
  ]
)

```

I still hit this

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'SupabaseStorage' from project 'Supabase')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'KeychainAccess' from project 'Supabase')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'KeychainAccess' from project 'Supabase')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'AnyCodable' from project 'Supabase')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Get' from project 'Supabase')
	CompileSwift normal arm64 (in target 'Get' from project 'Supabase')
(6 failures)
Error: xcodebuild exited with a non-zero code: 65

**Comment by johndpope** [comment]
https://github.com/apple/swift-package-manager/blob/main/Sources/SPMLLBuild/llbuild.swift

It maybe possible to reduce number  of xcframeworks by using this technique 
https://developer.apple.com/forums/thread/650995
You’d just need to modify a couple of lines in this library…. (I think)

**Comment by grsouza** [comment]
Supporting xcframework is not in the roadmap for now, we can revisit this later if priority changes.

**Comment by johndpope** [comment]
Hi @bok-  have you encountered any problems in general with xcframework / where the swift code that would automatically deallocate / BAD_EXEC - but run fine when code is ran locally? 
https://github.com/supabase-community/gotrue-swift/issues/32

![image](https://user-images.githubusercontent.com/289994/200156214-edba2755-e64f-4908-bb09-748f2210b78b.png)
