### ISSUE TITLE
Is it possible to authenticate using Twitter login?

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#39]
Hello,

Is it possible to sign up or login using  third party logins such as Twitter?
Thank you

**Comment by grsouza** [comment]
Hi @pradeepb28 

Yes, it is possible.

You can follow this tutorial https://supabase.com/docs/guides/auth/auth-twitter
And there is also an example for authentication with Google, and it would be similar for Twitter, you can check in the `gotrue` repository. https://github.com/supabase-community/gotrue-swift/blob/main/Examples/Shared/SignInWithGoogleExampleView.swift

**Comment by pradeepb28** [comment]
@grsouza it doesn't look like I can run on Xcode, any special instructions?

**Comment by pradeepb28** [comment]
@grsouza it doesn't look like I can run on Xcode, any special instructions?
