### ISSUE TITLE
systemModule is not supported - iPad Swift Playgrounds 4 

### ISSUE THREAD

**Issue by Rychillie** [supabase-community/supabase-swift#40]
I simply tried to install the package on Swift Playgrounds to study and it returned the error: ``The target type, “systemModule”, is not supported.``

<img width="1194" alt="Screenshot 2022-09-11 at 15 48 40" src="https://user-images.githubusercontent.com/14102456/189544129-aaee2050-3693-4ca9-a206-8e42742bbabf.png">

**Comment by cbunge3** [comment]
I get the same error as well - is this getting looked at?

**Comment by wmorgue** [comment]
I do not have this error in the latest `0.0.11` version. Tested on Swift Playground 4.2

**Comment by grsouza** [comment]
Thanks for the feedback @wmorgue, some dependencies have been removed on the latest versions that could have impacted this, I'll close it for now.
