### ISSUE TITLE
Clarification on signed in row level security access via jwt

### ISSUE THREAD

**Issue by johndpope** [supabase-community/supabase-swift#49]
# Improve documentation
  let client = SupabaseClient(supabaseURL: SUPABASE_URL, supabaseKey: ANON_KEY)

## Describe the problem
   how can a signed in user access database with row level security?
is there a way to switch in the jwt once we have it - 
eg.
 client.updateJWT( supabaseKey: authorisedJWT);

I'm working on a sign in with apple / nodejs - native login flow - but once I have the jwt - how can I then proceed to use it....
https://github.com/johndpope/Sign-in-with-Apple-for-supabase

**Comment by grsouza** [comment]
Hi, you can use `client.auth.setSession(accessToken: "jwt access token", refreshToken: "refresh_token")`

**Comment by johndpope** [comment]
cool - belongs in the readme.

**Comment by johndpope** [comment]
that is showing an error for me 
<img width="1568" alt="Screenshot 2022-11-18 at 6 46 41 am" src="https://user-images.githubusercontent.com/289994/202544409-4ea1e479-9fbb-4fae-8fb4-7e98288412ae.png">
<img width="402" alt="Screenshot 2022-11-18 at 6 47 35 am" src="https://user-images.githubusercontent.com/289994/202544502-3970a083-9ebb-4b7e-b3e9-6a59aa36436e.png">

**Comment by grsouza** [comment]
I think that's only available on `master` yet.

**Comment by johndpope** [comment]
making progress
<img width="1903" alt="Screenshot 2022-11-18 at 7 12 49 am" src="https://user-images.githubusercontent.com/289994/202549661-1082ab40-c5f7-4e9d-96df-b93cc99c457b.png">

**Comment by johndpope** [comment]
it would be good if there was an example for the provider url - is it supposed to be supabase url...? or self hosted?
