### ISSUE TITLE
Fails to build due to PostgREST master branch dependency

### ISSUE THREAD

**Issue by glowcap** [supabase-community/supabase-swift#52]
# Bug report

## Describe the bug

Build attempts fail due to changes in PostgREST master branch

- `FunctionsClient` init change
- `PostgrestClient` init change
- `FunctionsHTTPClient` removal
- `PostgrestHTTPClient` removal

## To Reproduce

1. Create new project (or have existing project)
2. Add supabase-swift SPM dependency as described in README
3. Attempt to build the project
4. See errors in `SupabaseClient.swift`

## Expected behavior

Should build without issue

## Screenshots

<img width="233" alt="Screenshot 2023-01-02 at 1 00 27 PM" src="https://user-images.githubusercontent.com/10408147/210270103-3692ea91-058c-4f5f-94a9-13b554c360c5.png">

## Additional context

Switching to the Release Candidate #45 most recent commit solves the issue (albeit not ideal)

`.package(name: "Supabase", url: "https://github.com/supabase/supabase-swift.git", branch: "release-candidate")`

It seems like shifting the master branch to tagged dependencies from here on would avoid issues like these popping up

**Comment by glowcap** [comment]
Created [PR](https://github.com/supabase-community/supabase-swift/pull/53) to resolve the issue

**Comment by grsouza** [comment]
PR merged and new release created with the following fix, https://github.com/supabase-community/supabase-swift/releases/tag/0.0.12

Thanks @glowcap .

---

Would be very nice if you used the release-candidate branch on your project, for helping catching any bugs on that.
