### ISSUE TITLE
Ability to add own headers

### ISSUE THREAD

**Issue by nyeu** [supabase-community/supabase-swift#56]
# Feature request

I am in the need to send my own `Authorization` token in the header rather than using the Auth session that Supabase provides and currently its impossible to do so - or I haven't found the way to do it. It would be interesting to be able to add your own custom headers in the init of the client since its where you set your `defaultHeaders`.

## Describe the solution you'd like

My proposal is to add in this init the ability to pass your own custom headers that are merged into the default Supabase ones. 
```
public init(
    supabaseURL: URL,
    supabaseKey: String,
    schema: String = "public",
    httpClient: HTTPClient = HTTPClient(),
customHeaders: [String: String]? = nil
  ) {
    self.supabaseURL = supabaseURL
    self.supabaseKey = supabaseKey
    self.schema = schema
    self.httpClient = httpClient

    defaultHeaders = [
      "X-Client-Info": "supabase-swift/\(version)",
      "apikey": supabaseKey,
    ]

if let customHeaders = customHeaders {
            defaultHeaders = defaultHeaders.merging(customHeaders) { (_, new) in new }
        }

    auth = GoTrueClient(
      url: supabaseURL.appendingPathComponent("/auth/v1"),
      headers: defaultHeaders
    )
  }

```
This way the user can overwrite the headers if they consider it so - at their own risk.

**Comment by guillego** [comment]
This would be really helpful! It would also follow the current behavior of the [supabase-js library](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L80).
