### ISSUE TITLE
SPM Error when compiling

### ISSUE THREAD

**Issue by silverfoxlabs** [supabase-community/supabase-swift#57]
# Bug report

## Describe the bug

The compiler complains when integrating ```supabase-swift``` into a project:

``` error: The package product 'Supabase' cannot be used as a dependency of this target because it uses unsafe build flags. (in target 'MyApp' from project 'MyApp') ```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new app in Xcode
2. Add swift package
3. Import the framework
4. Try to compile
5. See error above

## Expected behavior

Should be able to compile.

## System information

macOS Ventura 10.13.1
Xcode 14.2 (14C18)

**Comment by lhaenschke** [comment]
+1
I'm Having the same Error.

**Comment by grsouza** [comment]
Fixed on [release/0.1.2](https://github.com/supabase-community/supabase-swift/releases/tag/0.1.2), thanks for the report.
