### ISSUE TITLE
.list for Storage isnt working and supplying me anything

### ISSUE THREAD

**Issue by joshuabourke** [supabase-community/supabase-swift#66]
# Bug report

I am trying to run .list over a storage bucket to get back all the images or files inside of the bucket

check to see this discord conversation with myself and GaryAustin : https://discord.com/channels/839993398554656828/1082418604206739527

I can't seem to figure out why .list won't show any of my files and I can upload and download them.

**Comment by iamlouislab** [comment]
I think I found the issue and created a PR here: https://github.com/supabase-community/storage-swift/pull/13 where I proposed a fix.

**Comment by maail** [comment]
@joshuabourke this has been fixed in the latest release version for Storage thanks to @iamlouislab and @grsouza 

Take a look and you can close the issue if everything is good.

**Comment by joshuabourke** [comment]
@maail This works excellently! I just tried to out then!

Thank you for fixing this I am glad I could bring it to your attention.

Also, do you know when storage and swift will be ready for a production app?

**Comment by maail** [comment]
@joshuabourke All the functionality are there. We are just lacking in documentation which we are working on. 

If you have any issues just let us know, and we can figure it out and help to fix it.

**Comment by maail** [comment]
Since the main issue is resolved we are closing this.
