### ISSUE TITLE
OAuth Sign in with Apple (cannot open the page because the address is invalid)

### ISSUE THREAD

**Issue by joshuabourke** [supabase-community/supabase-swift#68]
I am trying to set up sign-in with apple for my Swift project. The account is being created on Supabase side but I can not see the email associated with the account.

trying to figure out what is the problem here and I am quite stumped. 

I think it could be that the NotificationCenter.default.post Isn't posting and there for the observer isn't working either

I have also opened a ticket in the discord: https://discord.com/channels/839993398554656828/1084966472163536926

**Comment by maail** [comment]
@joshuabourke can take a look at that. Can you post your code here so I can take a look? 

And could you elaborate more on you can't see the email associated with the account? Is it on Supbase?

**Comment by joshuabourke** [comment]
Yeah, I am unable to see the email that the user is using to sign up with apple. Supabase is seeing that there is an account being made.

The problem I am having is I don't think my app is posting or observing the notification.

I am also running the Observer on a button press.



<img width="1104" alt="Screenshot 2023-03-17 at 11 46 26 am" src="https://user-images.githubusercontent.com/24494726/225791140-9f9
<img width="891" alt="Screenshot 2023-03-17 at 11 47 23 am" src="https://user-images.githubusercontent.com/24494726/225791279-86c52a94-ccf7-44d5-8f94-63516823d453.png">
68af7-31b8-40b0-b593-ed73fd7c2ed3.png">

**Comment by joshuabourke** [comment]
<img width="1058" alt="Screenshot 2023-03-17 at 11 48 45 am" src="https://user-images.githubusercontent.com/24494726/225791482-141fbc7d-596b-4115-8e10-8fa8094d9b4b.png">


Sorry this was the other image.

**Comment by joshuabourke** [comment]
![simulator_screenshot_B06EDC7F-E81A-43D9-8003-7D8EFB7234FB](https://user-images.githubusercontent.com/24494726/225791592-c9213fff-c478-4fe2-b627-774c8bb77798.png)

After the user finishes signing in with apple. I am getting here, the Safari VC isn't dismissing so the oAuthCallback isn't getting fried.

**Comment by maail** [comment]
@joshuabourke Couple of things to checj:

1. What's the call back url you have setup on Supabase?
2. What's the url you are getting in scene openeURLContexts function?
3. Have you added the url in your Info.plist file? It should be under CFBundleURLSchemes if you check the source
