### ISSUE TITLE
Broken example in README.md

### ISSUE THREAD

**Issue by LawnmowerDave** [supabase-community/supabase-swift#70]
# Bug report

The CRUD insert example found in [README.MD](https://github.com/supabase-community/supabase-swift/blob/master/README.md) is broken. This caused a lot of frustration getting started. 

## Describe the bug

When running the example found in README.MD

```
let insertData = InsertModel(title: "Test", desc: "Test Desc")
let query = client.database
            .from("{ Your Table Name }")
            .select() // keep it empty for all, else specify returned data
            .match(query: ["title" : insertData.title, "desc": insertData.desc])
            .single()
            
Task {
    do {
        let response: InsertModel = try await query.execute().value
        print("### Returned: \(response)")
    } catch {
        print("### Insert Error: \(error)")
    }
}
```

Where `InsertModel` is defined as (as the README says "Using the same model as before")

```
struct InsertModel: Encodable {
    let id: Int? // you can choose to omit this depending on how you've setup your table
    let title: String?
    let desc: String?
}
```

You are greeted with the following error in XCode:

```
Cannot convert value of type 'Void' to specified type '[InsertModel]'
```

This is fixable by redefining `InsertModel` as follows:
```
struct InsertModel: Encodable, Decodable {
    let id: Int? // you can choose to omit this depending on how you've setup your table
    let title: String?
    let desc: String?
}
```

Which fixes this error. However, when attempting to cast to `InsertModel` as follows in the example:

```let response: InsertModel = try await query.execute().value```

You receive the following error

```
typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))
```

To address this, it must be fit into an array as follow:
```let response: [InsertModel] = try await query.execute().value```

This finally allows you to access the underlying data.

## To Reproduce

To reproduce, run the code found in the example README and perform the aforementioned changes.

## System information

- OS: [MacOS]
- Version of Supabase [0.1.3]
Using the Package.swift import:

```
let package = Package(
    ...
    dependencies: [
        ...
        .package(name: "Supabase", url: "https://github.com/supabase/supabase-swift.git", branch: "master"), // Add the package
    ],
    targets: [
        .target(
            name: "YourTargetName",
            dependencies: ["Supabase"] // Add as a dependency
        )
    ]
)
```

**Comment by maail** [comment]
Correct @LawnmowerDave looks like there were some issues as you mentioned above. Thanks for finding it out.

Would you mind raising a PR for the ReadMe with the correct code samples? Then we can get it merged.

**Comment by LawnmowerDave** [comment]
Will do, thanks for the response!
