### ISSUE TITLE
Searching across multiple columns (and matching substrings)

### ISSUE THREAD

**Issue by kevlust** [supabase-community/supabase-swift#73]
I have a table called `fun_facts` with the following columns:
`id`: int (primary key)
`content`: text
`keywords`: text
`tag`: text

Here's an example of a row:
`id`: 123
`content`: "A crocodile cannot stick its tongue out"
`keywords`: "impossible animals body funny"
`tag`: "fact123"

Using the Supabase Swift client, what's the **best/recommended way to search across multiple table columns**? I want the example row above to show up if I search for terms such as the following:
- "croc"
- "tongue crocodile"
- "animal funny"
- "impossible"
- "fact123"
- "123"

Thanks in advance!

**Comment by kevlust** [comment]
Figured this out!

**Comment by sarperdag** [comment]
Hey @kevlust , how did you figure this out?

**Comment by sarperdag** [comment]
Never mind, I also figured it out lol :)

**Comment by grdsdev** [comment]
@kevlust @sarperdag if you guys want to post the results you got, I can add an example to the repository, that may help other people in the future.

Thank you.
