### ISSUE TITLE
Which url should i use in redirect url to implement social auth?

### ISSUE THREAD

**Issue by igmyung** [supabase-community/supabase-swift#74]
which url should i use in redirect url in implementing social auth? Can u provide example?

**Comment by malachif-jpg** [comment]
If I am not mistaken the callback URL you need for any given social auth method can be found in your Supabase dashboard. Click the 'Authentication' tab on the left side of the screen, then click 'Providers', then click whatever service provider you want to use (Google in your case), then scroll to the bottom and you should see a field titled 'Redirect URL' that should look something like: 'https://<some_string>.supabase.co/auth/v1/callback', this is your callback URL.

Let me know if this was helpful.

**Comment by maail** [comment]
@igmyung if you've got this working let me know. And feel free to close after.

**Comment by grdsdev** [comment]
Hey @igmyung , if by redirect URL you mean the `redirectTo` parameter in some of the GoTrue methods, that would be a URL that your app can be redirected to, usually a URL scheme you set on Xcode, e.g. `my-app-scheme://`.

Note that this URL scheme must also be added to `Dashboard` -> `Authentication` -> `URL Configurations` -> `Redirect URLs`.

I hope that helps you, and I'll close the issue, if you need any further assistance, feel free to re-open it.

Thanks.
