### ISSUE TITLE
Can not create Client

### ISSUE THREAD

**Issue by SK4P3** [supabase-community/supabase-swift#83]
# Can't create client

## Client creation like in the readme doesn't work

I am trying to create a new client to test the supabase login in my swift-ui project, however when I try to create the client with:

`let client = SupabaseClient(supabaseURL: "{ Supabase URL }", supabaseKey: "{ Supabase anonymous Key }")` 

I get the error _Cannot convert value of type 'String' to expected argument type 'URL'_

When using `let client = SupabaseClient(supabaseURL: URL(string: "{ Supabase URL }"), supabaseKey: "{ Supabase anonymous Key }")` 

I get the error _No exact matches in call to initializer_ 

Am I doing something wrong or is the readme not up to date?

## Expected behavior

Create a client

## System information
- OS: macOS
- Version of supabase-switft: 0.2.1

**Comment by arclogos132** [comment]
I still get this error

**Comment by arclogos132** [comment]
https://github.com/supabase-community/supabase-swift/blob/master/Examples/Examples/_Secrets.swift
