### ISSUE TITLE
Login with Apple ID (no SafariVC) and subsequent use of access_token

### ISSUE THREAD

**Issue by josefrichter** [supabase-community/supabase-swift#89]
I figured out a way how to authenticate a user using the standard `SignInWithAppleButton` without needing any webviews. This code works:

The Apple button will return `credential: ASAuthorizationAppleIDCredential` that contains `credential.identityToken` which is then passed to the following function:

```swift
func loginWithAppleViaSupabase(_ idToken: Data, completion: @escaping (User?) -> Void) {
        // URL to the Supabase endpoint for token authentication
        guard let requestUrl = URL(string: "\(self.supabaseURLString)/auth/v1/token?grant_type=id_token") else {
            fatalError("Invalid URL")
        }
        
        // Prepare HTTP request
        var request = URLRequest(url: requestUrl)
        request.httpMethod = "POST"
        request.setValue(self.supabaseKey, forHTTPHeaderField: "apikey") // Replace with your API key
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
        
        // Convert idToken Data to String
        guard let idTokenString = String(data: idToken, encoding: .utf8) else {
            print("Unable to serialize token string from data: \(idToken.debugDescription)")
            return
        }
        print("idTokenString:", idTokenString)
        
        // Prepare parameters for HTTP Request Body
        let parameters = [
            "provider": "apple",
            "id_token": idTokenString,
            "options": ""
        ]
        
        // Encode parameters to JSON and set as HTTP Request Body
        do {
            request.httpBody = try JSONEncoder().encode(parameters)
        } catch {
            print("Failed to encode parameters: \(error)")
            return
        }
        print("parameters:", parameters)
        
        // Send HTTP Request
        let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
            // Check for Error
            if let error = error {
                print("Error took place \(error)")
                completion(nil)
                return
            }
            
            // Convert HTTP Response Data to a String and print it
            if let data = data, let dataString = String(data: data, encoding: .utf8) {
                print("Response data string:\n \(dataString)")
                
                do {
                    
                    let decoder = JSONDecoder()
                    let tokenResponse = try decoder.decode(TokenResponse.self, from: data)
                    var user = tokenResponse.user
                    user.accessToken = tokenResponse.accessToken
                    user.refreshToken = tokenResponse.refreshToken
                    
                    // Use the user object here
                    print("User id: \(user.id)")
                    print("User email: \(user.email ?? "N/A")")

                    completion(user)
                    
                } catch {
                    print("Error decoding data: \(error)")
                    completion(nil)
                }
            }
        }
        task.resume()
    }
```
    
As you can see, the response I get also includes the access_token that is needed for subsequent API calls. However, I don't know how to add it to those calls.

I noticed in source code the `adapt` function that requests current session and adds the access_token to requests, but I am not sure how to actually use it. My way of authenticating the user seems a bit non-standard and undocumented, and the next step is slightly beyond my skillset. 

Am I missing something in the documentation? How do I add access_token to all further requests? Thank you.

**Comment by josefrichter** [comment]
I think I just found the solution. There's

`client.auth.setSession(accessToken: String, refreshToken: String)`

That needs to be called with the tokens received using Apple Button.

Maybe this flow is worth documenting?

**Comment by lucabeetz** [comment]
Do you know how to store additional user data on user creation with this? For example the user name you get when first logging in with `request.requestedScopes = [.fullName, .email]` set.

**Comment by hilzfa** [comment]
> Hey Josef, thanks for posting this authentication flow!
> 
> I am able to get the access and refresh tokens from the response and a new user is created in the database. However, when I try to query any data using the following example code from the repo I get a void response. I am not sure if this is related to the authentication. I do run `try await self.supabaseClient.auth.setSession(accessToken: accessToken, refreshToken: refreshToken)` before querying data. Do you know why this might happen? I have disabled RLS for debugging.
> 
> ```swift
> let query = supabaseClient.database
>     .from("images")
>     .select()
> 
> Task {
>     do {
>         let response = try await query.execute().value
>         print("Returned: \(response)")
>     } catch {
>         print("Error: \(error)")
>     }
> }
> ```
> 
> EDIT: Fixed this, the problem was unrelated to auth. I missed the `Encodable, Decodable` on my models.

Thanks @lucabeetz for the `Encodable, Decodable` hint. I was not aware of the fact that a model is mandatory to retrieve data from database.

**Comment by malachif-jpg** [comment]
@josefrichter Is your TokenResponse object a custom object? If so, could you provide us an example?

**Comment by MexJason** [comment]
Hey everyone, I recently made a video on how to to implement the native sign in with apple using SwiftUI. The approach should be very similar in UIKit. I will link to it below!

https://www.youtube.com/watch?v=cmobs7KLyjI&t=1s

**Comment by grsouza** [comment]
I added an example of this on GoTrue repository, check it out https://github.com/supabase-community/gotrue-swift/pull/62f

**Comment by hongminpark** [comment]
Thanks @grsouza ! 
Anyone who couldn't figure out how to do, I used this swiftUI code.
(Code referenced from https://github.com/supabase-community/gotrue-swift/tree/main/Examples)

Currently, supabase client go-true's `signInWithIdToken` function is marked as `Experimental` so can't use directly. Need to import like this : `@_spi(Experimental) import GoTrue`. 

```
import SwiftUI
import AuthenticationServices
import Supabase
@_spi(Experimental) import GoTrue

struct SignInView: View {
    let client = SupabaseClient(supabaseURL: URL(string: "your url")!, supabaseKey: "your key")

    var body: some View {
      SignInWithAppleButton { request in
        request.requestedScopes = [.email, .fullName]
      } onCompletion: { result in
        Task {
          do {
            guard let credential = try result.get().credential as? ASAuthorizationAppleIDCredential
            else {
              return
            }

            guard let idToken = credential.identityToken
              .flatMap({ String(data: $0, encoding: .utf8) })
            else {
              return
            }
              try await client.auth.signInWithIdToken(
              credentials: .init(
                provider: .apple,
                idToken: idToken
              )
            )
          } catch {
            dump(error)
          }
        }
      }
      .fixedSize()
    }
}
```
