### ISSUE TITLE
Update column to null

### ISSUE THREAD

**Issue by wil2106** [supabase-community/supabase-swift#93]
Hello,
I'm trying to update a column to NULL with Supabase Swift Client by setting the object property to nil, but the update ignores it.
Is there a way to do it ?

**Comment by grsouza** [comment]
That's, unfortunately, an issue with how JSONEncoder works, check this thread (https://stackoverflow.com/questions/47266862/encode-nil-value-as-null-with-jsonencoder).

Use the `NullEncodable` type proposed at (https://stackoverflow.com/a/62312021) as a workaround.
