### ISSUE TITLE
Session storage

### ISSUE THREAD

**Issue by pradeepb28** [supabase-community/supabase-swift#98]
# Feature request
Currently it seems like once I receive the session, it doesn't store on the device. In such case I am storing using userdefaults on the device.

As soon as user signed up or logged in, session should be stored locally on the device that persists between app opening should be a out of box solution from the library

**Comment by grsouza** [comment]
Hey, @pradeepb28 the library should store the session using the keychain by default, do you have more information regarding the issue you're having?

Any log message or report?
