### ISSUE TITLE
Sign In With Apple Id Token.

### ISSUE THREAD

**Issue by joshuabourke** [supabase-community/supabase-swift#99]
Hey, I know that sign-in with Apple Id Token was marked Experimental. I was just wanting to know when it will become available again for use.

Also, I am unsure if I am able to continue using this method. If I am would you be able to show me an example of how to get around this @_spi(Experimental) error?

```swift
  /// Allows signing in with an ID token issued by certain supported providers.
  /// The ID token is verified for validity and a new session is established.
  @_spi(Experimental)
  @discardableResult
  public func signInWithIdToken(credentials: OpenIDConnectCredentials) async throws -> Session {
    try await _signIn(
      request: Paths.token.post(
        grantType: .idToken,
        .openIDConnectCredentials(credentials)
      )
    )
  }
```

My Code which is now erroring:

```swift
try await client.auth.signInWithIdToken(credentials: .init(provider: .apple, idToken: idToken, nonce: nonce))
```

**Comment by grsouza** [comment]
Hey @joshuabourke you need to import the library as `@_spi(Experimental) import GoTrue`.
